### ISSUE TITLE
Join forces: USDB Syncer

### ISSUE THREAD

**Issue by marwin89** [EinEisbxr/ultrastar_downloader#12]
Hi Felix, hi emil 👋🏻 🙂
This looks like a cool project. Did you know that there is a quite similiar project called "USDB Syncer"?
https://github.com/bohning/usdb_syncer
Maybe you could co-work together. It's also written in python. Lead is Markus Bohning (I guess there are 3 team members). They always looking for new contributors.
You can also join UltraStar, Vocaluxe, Performous Community to talk with them in "USDB-Syncer"-Channel.
https://discord.gg/tNEXZw2QJX

**Comment by EinEisbxr** [comment]
Hey,
I will look into it, I already joined the discord. Should I contact them there?

**Comment by marwin89** [comment]
nice :) yes, just say hello in USDB-Syncer-related channel and say that you're interessted to join/co-work. Mention @bohning. I've told him, that you have a similar project. He is quite active on this discord.
